// user login constant
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILD = "USER_LOGIN_FAILD";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILD = "USER_REGISTER_FAILD";

export const MOVIES_DETAIL = "MOVIES_DETAIL";
export const MOVIES_DETAIL_SUCCESS = "MOVIES_DETAIL_SUCCESS";
export const MOVIES_DETAIL_FAILD = "MOVIES_DETAIL_FAILD";

export const MOVIE_DETAIL = "MOVIE_DETAIL";
export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAIL_FAILD = "MOVIE_DETAIL_FAILD";

export const ADD_NEW = "ADD_NEW";
export const ADD_NEW_SUCCESS = "ADD_NEW_SUCCESS";
export const ADD_NEW_FAILD = "ADD_NEW_FAILD";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILD = "USER_LOGOUT_FAILD";

export const DELETE = "DELETE";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILD = "DELETE_FAILD";

export const UPDATE = "UPDATE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILD = "UPDATE_FAILD";